spring:
  application:
    name: horadaprotecao-test

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: localhost
    port: 1025
    username: test@fake.com
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        provider:
          fiap-keycloak:
            issuer-uri: http://localhost:8080/realms/test-realm
        registration:
          keycloak:
            provider: fiap-keycloak
            authorization-grant-type: authorization_code
            client-id: test-client
            client-secret: test-secret
            scope: openid

server:
  port: 0 # Porta aleatória para testes

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 0.0
  otel:
    tracing:
      enabled: false

otel:
  exporter:
    jaeger:
      endpoint: http://localhost:14250
  resource:
    attributes:
      service.name: horadaprotecao-test

logging:
  level:
    root: WARN
    br.com.fiap: DEBUG
